<a href="https://colab.research.google.com/github/2303A52085/generative-AI/blob/main/ASS_8.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [2]:
import pandas as pd
import numpy as np
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler

# Load dataset (Make sure to provide the correct path to the dataset)
data = pd.read_csv('winequality-red.csv')

# Preview the data
data.head()

# Assuming the last column is the target variable 'quality'
X = data.drop('quality', axis=1)  # Features
y = data['quality']  # Target variable

# Scale the features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(X)

# Split data into training and testing sets
X_train, X_test, y_train, y_test = train_test_split(X_scaled, y, test_size=0.2, random_state=42)

In [3]:
from keras.models import Sequential
from keras.layers import Dense
from keras.optimizers import Adadelta

# Define the model
model = Sequential()

# Hidden Layer 1: 16 neurons, 'relu' activation
model.add(Dense(16, input_dim=X_train.shape[1], activation='relu'))

# Hidden Layer 2: 20 neurons, 'relu' activation
model.add(Dense(20, activation='relu'))

# Hidden Layer 3: 25 neurons, 'relu' activation
model.add(Dense(25, activation='relu'))

# Hidden Layer 4: 10 neurons, 'relu' activation
model.add(Dense(10, activation='relu'))

# Output layer: Assuming it's a classification problem, so we use 'softmax' (or 'sigmoid' if binary)
model.add(Dense(1, activation='sigmoid'))  # If this is a binary classification problem

# Compile the model
model.compile(loss='binary_crossentropy', optimizer=Adadelta(), metrics=['accuracy'])

/usr/local/lib/python3.11/dist-packages/keras/src/layers/core/dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)


In [4]:
# Train the model
history = model.fit(X_train, y_train, epochs=100, batch_size=64, validation_data=(X_test, y_test))

Epoch 1/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 3s 22ms/step - accuracy: 0.0000e+00 - loss: 2.0647 - val_accuracy: 0.0000e+00 - val_loss: 2.1404
Epoch 2/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.0000e+00 - loss: 2.1218 - val_accuracy: 0.0000e+00 - val_loss: 2.1334
Epoch 3/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.0000e+00 - loss: 2.1256 - val_accuracy: 0.0000e+00 - val_loss: 2.1263
Epoch 4/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.0000e+00 - loss: 2.1338 - val_accuracy: 0.0000e+00 - val_loss: 2.1191
Epoch 5/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.0000e+00 - loss: 2.0336 - val_accuracy: 0.0000e+00 - val_loss: 2.1119
Epoch 6/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.0000e+00 - loss: 2.0572 - val_accuracy: 0.0000e+00 - val_loss: 2.1045
Epoch 7/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - accuracy: 0.0000e+00 - loss: 2.0493 - val_accuracy: 0.0000e+00 - val_loss: 2.0970
Epoch 8/100
20/20 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step - a

In [5]:
# 2-Question
from sklearn.metrics import confusion_matrix, classification_report

# Evaluate the model
train_accuracy = model.evaluate(X_train, y_train)
test_accuracy = model.evaluate(X_test, y_test)

# Make predictions
y_pred = model.predict(X_test)
y_pred = (y_pred > 0.5)  # Convert probabilities to binary labels

# Confusion matrix
cm = confusion_matrix(y_test, y_pred)

# Classification report
report = classification_report(y_test, y_pred)

# Print results
print(f"Training Accuracy: {train_accuracy[1]*100:.2f}%")
print(f"Testing Accuracy: {test_accuracy[1]*100:.2f}%")
print("Confusion Matrix:\n", cm)
print("Classification Report:\n", report)

40/40 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step - accuracy: 0.0000e+00 - loss: 1.1149
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 5ms/step - accuracy: 0.0000e+00 - loss: 1.1768 
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step 
Training Accuracy: 0.00%
Testing Accuracy: 0.00%
Confusion Matrix:
 [[ 0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0]
 [ 1  0  0  0  0  0  0  0]
 [ 8  2  0  0  0  0  0  0]
 [87 43  0  0  0  0  0  0]
 [99 33  0  0  0  0  0  0]
 [37  5  0  0  0  0  0  0]
 [ 5  0  0  0  0  0  0  0]]
Classification Report:
               precision    recall  f1-score   support

           0       0.00      0.00      0.00       0.0
           1       0.00      0.00      0.00       0.0
           3       0.00      0.00      0.00       1.0
           4       0.00      0.00      0.00      10.0
           5       0.00      0.00      0.00     130.0
           6       0.00      0.00      0.00     132.0
           7       0.00      0.00      0.00      42.0
           8       0.00      0.00      0.00       5.0

    accu

/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Recall is ill-defined and being set to 0.0 in labels with no true samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_classification.py:1565: UndefinedMetricWarning: Precision is ill-defined and being set to 0.0 in labels with no predicted samples. Use `zero_division` parameter to control this behavior.
  _warn_prf(average, modifier, f"{metric.capitalize()} is", len(result))
/usr/local/lib/python3.11/dist-packages/sklearn/metrics/_

In [6]:
# Save the model to a file
model.save('wine_quality_model.h5')

In [7]:
# Example: Predict quality for new data (you need to preprocess this new data)
# Removed the last value which is likely the quality score to keep 11 features only.
# The error was due to passing 12 features to the StandardScaler that was fitted on 11 features
# Fix: Remove one of the values from the feature list, potentially the last one if it is the quality.
new_data = np.array([[7.4, 0.7, 0.0, 1.9, 0.074, 16.0, 96.0, 0.68, 0.0, 9.4, 0.52]])  # Example input with 11 features

new_data_scaled = scaler.transform(new_data)  # Scale the new data

# Predict the wine quality
prediction = model.predict(new_data_scaled)
print("Predicted Quality:", prediction[0][0])  # The prediction value

1/1 ━━━━━━━━━━━━━━━━━━━━ 0s 83ms/step
Predicted Quality: 0.99814206


/usr/local/lib/python3.11/dist-packages/sklearn/utils/validation.py:2739: UserWarning: X does not have valid feature names, but StandardScaler was fitted with feature names
  warnings.warn(
